# Generated by Django 2.2.1 on 2019-05-08 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doner', '0010_auto_20190508_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('Cairo ,Egypt', 'Cairo'), ('Mansoura ,Egypt', 'Mansoura'), ('Arish ,Egypt', 'Arish'), ('Ismailia ,Egypt', 'Ismailia'), ('Alexandria ,Egypt', 'Alexandria'), ('Aswan ,Egypt', 'Aswan'), ('Asyut ,Egypt', 'Asyut'), ('Beheira ,Egypt', 'Damanhur'), ('Beni Suef ,Egypt', 'Beni Suef'), ('Faiyum ,Egypt', 'Faiyum'), ('Gharbia ,Egypt', 'Tanta'), ('Giza ,Egypt', 'Giza'), ('Kafr El Sheikh ,Egypt', 'Kafr El Sheikh'), ('Matruh ,Egypt', 'Marsa Matruh '), ('Monufia ,Egypt', 'Shibin El Kom')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4)),
                ('request_status', models.CharField(choices=[('0', 'REJECT'), ('1', 'ACCEPT')], default='0', editable=False, max_length=1)),
                ('patients_status', models.CharField(choices=[('1', 'Normal'), ('2', 'Urgent'), ('3', 'Immediate')], max_length=1)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doner.Bank')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital')),
            ],
        ),
    ]
