# Generated by Django 2.2.1 on 2019-05-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestblood',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doner.Bank'),
        ),
        migrations.AlterField(
            model_name='requestblood',
            name='request_status',
            field=models.CharField(choices=[('0', 'REJECT'), ('1', 'ACCEPT'), ('2', 'Append')], default='2', max_length=1),
        ),
    ]
