# Generated by Django 2.2.1 on 2019-05-07 19:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Cairo ,Egypt', 'Cairo'), ('Mansoura ,Egypt', 'Mansoura'), ('Arish ,Egypt', 'Arish'), ('Ismailia ,Egypt', 'Ismailia')], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4)),
                ('blood_expiration', models.DateTimeField(default=datetime.datetime(2019, 7, 6, 19, 38, 21, 415694), editable=False)),
                ('test_state', models.CharField(choices=[('0', 'NAGATIVE'), ('1', 'PPSTIVE')], max_length=1)),
                ('doner_status', models.CharField(choices=[('1', 'ACCEPT'), ('0', 'REFUSE')], max_length=1)),
                ('donation_status', models.CharField(choices=[('1', 'ACCEPT'), ('0', 'REFUSE')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doner.Bank')),
                ('doner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doner.Doner')),
            ],
        ),
    ]
