# Generated by Django 2.2.1 on 2019-05-07 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0003_auto_20190507_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 19, 39, 56, 802538), editable=False),
        ),
    ]
