# Generated by Django 2.2.1 on 2019-05-07 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0006_auto_20190507_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 21, 30, 7, 780480), editable=False),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='last_donate_date',
            field=models.DateField(),
        ),
    ]
