# Generated by Django 2.2.1 on 2019-05-07 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0007_auto_20190507_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 21, 53, 20, 753716), editable=False),
        ),
    ]
