# Generated by Django 2.2.1 on 2019-05-07 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0008_auto_20190507_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 22, 15, 40, 583795), editable=False),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='doner_status',
            field=models.CharField(choices=[('1', 'More Then 3 Month'), ('0', 'Less Then 3 Month')], default='1', editable=False, max_length=1, verbose_name='Last Donate '),
        ),
    ]
