# Generated by Django 2.2.1 on 2019-05-08 08:38

import Doner.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doner', '0009_auto_20190507_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 8, 38, 12, 913254), editable=False),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='doner_status',
            field=models.CharField(choices=[('1', 'More Then 3 Month'), ('0', 'Less Then 3 Month')], default='1', max_length=1, verbose_name='Last Donate '),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='last_donate_date',
            field=models.DateField(validators=[Doner.models.validate_last_donate_date]),
        ),
        migrations.AlterField(
            model_name='doner',
            name='national_id',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
